const galleryInfo = {
  groupProjects: [
    {
      projectId: 1,
      groupName: '구름',
      groupImage: 'https://image.ajunews.com/content/image/2024/01/21/20240121132054894779.jpg',
      projectName: '모두의 자율',
      projectImage: 'https://image.ajunews.com/content/image/2024/01/21/20240121132054894779.jpg',
      projectDescription: '모두의 자율학습, 모자는 생성형 AI를 통해 맞춤형 문제를 생성합니다.',
      views: 55,
      likes: 77,
      comments: 11,
    },
    {
      projectId: 4,
      groupName: '구름',
      groupImage: '/images/group-image.jpg',
      projectName: '피클',
      projectImage: 'path/to/project-image.jpg',
      projectDescription: '피클은 클라우드 배포 서비스입니다.',
      views: 55,
      likes: 77,
      comments: 11,
    },
    {
      projectId: 9,
      groupName: '구름',
      groupImage: '/images/group-image.jpg',
      projectName: '로컬 라이프',
      projectImage: 'path/to/project-image.jpg',
      projectDescription: '로컬라이프는 지방에서 한달살기 프로젝트.',
      views: 55,
      likes: 77,
      comments: 11,
    },
    {
      projectId: 99,
      groupName: '구름',
      groupImage: '/images/group-image.jpg',
      projectName: '로컬 라이프',
      projectImage: 'path/to/project-image.jpg',
      projectDescription: '로컬라이프는 지방에서 한달살기 프로젝트.',
      views: 55,
      likes: 77,
      comments: 11,
    },
    {
      projectId: 100,
      groupName: '구름',
      groupImage: '/images/group-image.jpg',
      projectName: '로컬 라이프',
      projectImage: 'path/to/project-image.jpg',
      projectDescription: '로컬라이프는 지방에서 한달살기 프로젝트.',
      views: 55,
      likes: 77,
      comments: 11,
    },
    {
      projectId: 101,
      groupName: '솔라',
      groupImage: 'https://image.example.com/group-image1.jpg',
      projectName: '태양광 발전',
      projectImage: 'https://image.example.com/project-image1.jpg',
      projectDescription: '태양광 발전 프로젝트, 지속 가능한 에너지를 연구합니다.',
      views: 120,
      likes: 200,
      comments: 30,
    },
    {
      projectId: 102,
      groupName: '에코',
      groupImage: 'https://image.example.com/group-image2.jpg',
      projectName: '에코 농업',
      projectImage: 'https://image.example.com/project-image2.jpg',
      projectDescription: '에코 농업 프로젝트, 자연 친화적인 농업 방법을 개발합니다.',
      views: 300,
      likes: 450,
      comments: 80,
    },
    {
      projectId: 103,
      groupName: '헬스케어',
      groupImage: 'https://image.example.com/group-image3.jpg',
      projectName: '건강 관리 앱',
      projectImage: 'https://image.example.com/project-image3.jpg',
      projectDescription: '개인 맞춤형 건강 관리 앱을 개발하여 사용자의 건강을 관리합니다.',
      views: 220,
      likes: 310,
      comments: 45,
    },
    {
      projectId: 104,
      groupName: '교육혁신',
      groupImage: 'https://image.example.com/group-image4.jpg',
      projectName: '디지털 교과서',
      projectImage: 'https://image.example.com/project-image4.jpg',
      projectDescription: '디지털 교과서를 개발하여 학습자에게 보다 효율적인 학습 환경을 제공합니다.',
      views: 180,
      likes: 250,
      comments: 33,
    },
    {
      projectId: 105,
      groupName: '스마트시티',
      groupImage: 'https://image.example.com/group-image5.jpg',
      projectName: '스마트 주차 시스템',
      projectImage: 'https://image.example.com/project-image5.jpg',
      projectDescription: '스마트 주차 시스템을 개발하여 도시의 교통 문제를 해결합니다.',
      views: 145,
      likes: 210,
      comments: 25,
    },
    {
      projectId: 106,
      groupName: 'AI 연구소',
      groupImage: 'https://image.example.com/group-image6.jpg',
      projectName: 'AI 기반 번역기',
      projectImage: 'https://image.example.com/project-image6.jpg',
      projectDescription: '최신 AI 기술을 활용한 실시간 번역기 개발 프로젝트.',
      views: 500,
      likes: 600,
      comments: 90,
    },
  ],
};

export default galleryInfo;
